### PR TITLE
Send / Receive SMS with new google voice API

### PR DESCRIPTION
**Pull request by tobocop2**
## Send / Receive SMS with new google voice API

* Send and retrieve sms with the new api 
  
* Implement dynamic hash generation for all requests

* Add api_key config option for new google voice api key
  Note: this is now a requirement. See screenshots for retreiving API key

This plugin now supports group texts: see screenshot below

GroupMessage

## Notes:
* Removed beautifulsoup dependency 
* New API provides drastic speed up and allows for very easy conversation pagination. 

## TODOS: 
* Either: 
  A) remove pygooglevoice dependency as it is only used for login now 
  B) ideally, make necessary updates to pygoogle voice to wrap around new API

* Figure out how to retrieve API key automatically. 

## Retrieving api key

The simplest way is to go to the developer tools in your browser and to see the requests
being sent. See screenshots below

#### Chromium 71.0.3578.98 Arch Linux
chromium

#### Mozilla Firefox 64.0.2
firefox

### CODE REVIEW

**Comment by tych0** [comment]
I sort of doubt you can generate an API key, or at least, it won't be as easy as an "API" call as the other things are. Presumably users need to do that themselves?

**Comment by tobocop2** [comment]
Since it's not a public API, the api key is of unknown origin. It's not something I generated using the google developer API. I grabbed the API key by just looking at the post requests coming from my browser. It's in the query string to every request. 

I suspect it could be generated on the client side using one of the headers, similar to the SAPISID HASH value I needed to generate as part of the "Authorization" header. 

If it's generated by the server, then it won't be possible to get dynamically, but I haven't made that conclusion yet. It would be a minor inconvenience to retrieve this API key for the end user, but I still would like to see if I could figure out where it's coming from before giving up. It's been painful digging through beautified minified javascript haha.

**Comment by tych0** [comment]
Let me know if you're ready to merge this, I'm happy to merge it.

**Comment by tobocop2** [comment]
@tych0 
Thanks. I created a PR to the official repo. You can merge or close it if you like. I will merge this PR into my fork myself.

**Pull request merged**
